//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 10:35:54 PM EET 
//

package pixeleon.khpi.oop.fmd.model.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FFunctionData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FFunctionTerm" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="Degree" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="Coeff" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="GFunctionData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="GFunctionPair" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="X" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                           &lt;attribute name="YofX" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "fFunctionData", "gFunctionData" })
@XmlRootElement(name = "EquationData")
public class EquationData {

	@XmlElement(name = "FFunctionData", required = true)
	protected EquationData.FFunctionData fFunctionData;
	@XmlElement(name = "GFunctionData", required = true)
	protected EquationData.GFunctionData gFunctionData;

	/**
	 * Gets the value of the fFunctionData property.
	 * 
	 * @return possible object is {@link EquationData.FFunctionData }
	 * 
	 */
	public EquationData.FFunctionData getFFunctionData() {
		return fFunctionData;
	}

	/**
	 * Sets the value of the fFunctionData property.
	 * 
	 * @param value allowed object is {@link EquationData.FFunctionData }
	 * 
	 */
	public void setFFunctionData(EquationData.FFunctionData value) {
		this.fFunctionData = value;
	}

	/**
	 * Gets the value of the gFunctionData property.
	 * 
	 * @return possible object is {@link EquationData.GFunctionData }
	 * 
	 */
	public EquationData.GFunctionData getGFunctionData() {
		return gFunctionData;
	}

	/**
	 * Sets the value of the gFunctionData property.
	 * 
	 * @param value allowed object is {@link EquationData.GFunctionData }
	 * 
	 */
	public void setGFunctionData(EquationData.GFunctionData value) {
		this.gFunctionData = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="FFunctionTerm" maxOccurs="unbounded">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;attribute name="Degree" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *                 &lt;attribute name="Coeff" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "fFunctionTerm" })
	public static class FFunctionData {

		@XmlElement(name = "FFunctionTerm", required = true)
		protected List<EquationData.FFunctionData.FFunctionTerm> fFunctionTerm;

		/**
		 * Gets the value of the fFunctionTerm property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot.
		 * Therefore any modification you make to the returned list will be present
		 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
		 * for the fFunctionTerm property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getFFunctionTerm().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link EquationData.FFunctionData.FFunctionTerm }
		 * 
		 * 
		 */
		public List<EquationData.FFunctionData.FFunctionTerm> getFFunctionTerm() {
			if (fFunctionTerm == null) {
				fFunctionTerm = new ArrayList<EquationData.FFunctionData.FFunctionTerm>();
			}
			return this.fFunctionTerm;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content contained within
		 * this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;attribute name="Degree" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
		 *       &lt;attribute name="Coeff" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class FFunctionTerm {

			@XmlAttribute(name = "Degree", required = true)
			protected int degree;
			@XmlAttribute(name = "Coeff", required = true)
			protected double coeff;

			/**
			 * Gets the value of the degree property.
			 * 
			 */
			public int getDegree() {
				return degree;
			}

			/**
			 * Sets the value of the degree property.
			 * 
			 */
			public void setDegree(int value) {
				this.degree = value;
			}

			/**
			 * Gets the value of the coeff property.
			 * 
			 */
			public double getCoeff() {
				return coeff;
			}

			/**
			 * Sets the value of the coeff property.
			 * 
			 */
			public void setCoeff(double value) {
				this.coeff = value;
			}

		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="GFunctionPair" maxOccurs="unbounded">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;attribute name="X" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
	 *                 &lt;attribute name="YofX" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "gFunctionPair" })
	public static class GFunctionData {

		@XmlElement(name = "GFunctionPair", required = true)
		protected List<EquationData.GFunctionData.GFunctionPair> gFunctionPair;

		/**
		 * Gets the value of the gFunctionPair property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot.
		 * Therefore any modification you make to the returned list will be present
		 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
		 * for the gFunctionPair property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getGFunctionPair().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link EquationData.GFunctionData.GFunctionPair }
		 * 
		 * 
		 */
		public List<EquationData.GFunctionData.GFunctionPair> getGFunctionPair() {
			if (gFunctionPair == null) {
				gFunctionPair = new ArrayList<EquationData.GFunctionData.GFunctionPair>();
			}
			return this.gFunctionPair;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content contained within
		 * this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;attribute name="X" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
		 *       &lt;attribute name="YofX" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class GFunctionPair {

			@XmlAttribute(name = "X", required = true)
			protected double x;
			@XmlAttribute(name = "YofX", required = true)
			protected double yofX;

			/**
			 * Gets the value of the x property.
			 * 
			 */
			public double getX() {
				return x;
			}

			/**
			 * Sets the value of the x property.
			 * 
			 */
			public void setX(double value) {
				this.x = value;
			}

			/**
			 * Gets the value of the yofX property.
			 * 
			 */
			public double getYofX() {
				return yofX;
			}

			/**
			 * Sets the value of the yofX property.
			 * 
			 */
			public void setYofX(double value) {
				this.yofX = value;
			}

		}

	}

}
