//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 10:35:54 PM EET 
//

package pixeleon.khpi.oop.fmd.model.xml;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the pixeleon.khpi.oop.fmd.model.xml
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema
	 * derived classes for package: pixeleon.khpi.oop.fmd.model.xml
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link EquationData }
	 * 
	 */
	public EquationData createEquationData() {
		return new EquationData();
	}

	/**
	 * Create an instance of {@link EquationData.GFunctionData }
	 * 
	 */
	public EquationData.GFunctionData createEquationDataGFunctionData() {
		return new EquationData.GFunctionData();
	}

	/**
	 * Create an instance of {@link EquationData.FFunctionData }
	 * 
	 */
	public EquationData.FFunctionData createEquationDataFFunctionData() {
		return new EquationData.FFunctionData();
	}

	/**
	 * Create an instance of {@link EquationData.GFunctionData.GFunctionPair }
	 * 
	 */
	public EquationData.GFunctionData.GFunctionPair createEquationDataGFunctionDataGFunctionPair() {
		return new EquationData.GFunctionData.GFunctionPair();
	}

	/**
	 * Create an instance of {@link EquationData.FFunctionData.FFunctionTerm }
	 * 
	 */
	public EquationData.FFunctionData.FFunctionTerm createEquationDataFFunctionDataFFunctionTerm() {
		return new EquationData.FFunctionData.FFunctionTerm();
	}

}
